### ISSUE TITLE
Redeploy @swc/helpers with @swc/core@1.2.52

### ISSUE THREAD

**Issue by grimly** [swc-project/helpers#4]
Due to a bug fixed by swc-project/swc#1550, commonjs code in @swc/helpers@0.2.5 is invalid.

Here is a sample: https://unpkg.com/browse/@swc/helpers@0.2.5/lib/_wrap_native_super.js
`_wrapNativeSuper1` is not a valid reference.

Also wrapper functions applied in #3 are missing. I'll open a new issue regarding this.

**Comment by grimly** [comment]
Wrapper functions are kept intact when using `@swc/core@1.2.52`, therefore everything should be fine

**Comment by kdy1** [comment]
I deployed a new version. Thanks!

**Comment by grimly** [comment]
Hello again.

I think something went wrong with the build.

I'll take again `_wrap_native_super.js` as an example.

Here is the current version deployed : https://unpkg.com/browse/@swc/helpers@0.2.7/lib/_wrap_native_super.js

When I checkout and build myself, I get these last lines:

```javascript
        return _setPrototypeOf.default(Wrapper, Class1);
    };
    return wrapNativeSuper(Class);
}
function _wrapNativeSuper(Class) {
    return wrapNativeSuper(Class);
}
exports.default = _wrapNativeSuper;
```

Can you deploy again checking the dependencies version from `node_modules` ?

Best regards.

**Comment by kdy1** [comment]
I redeployed it (many times), and https://unpkg.com/browse/@swc/helpers@0.2.10/lib/_wrap_native_super.js now shows expected results :)
